name: tarok
description: Tarok program Palčka
publish_to: "none"

version: 0.0.5+5

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: 2.1.0

  cupertino_icons: ^1.0.2
  web_socket_client:
  dio: ^5.0.1
  flutter_secure_storage: ^8.0.0
  web_socket_channel: ^2.3.0
  copy_with_extension: ^5.0.0
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.10
  flutter_svg: ^2.0.4
  flutter_phoenix: ^1.1.1
  logger: ^2.0.1
  shared_preferences: ^2.2.0
  settings_ui: ^2.0.2
  stockskis:
    path: ../stockskis
  flutter_initicon: ^3.0.0+1
  rounded_background_text: ^0.3.0
  draggable_widget:
    git:
      url: https://github.com/mytja/draggable_widget
      ref: master
  media_kit: ^1.1.7
  media_kit_libs_audio: ^1.0.1
  get:
  url_strategy: ^0.2.0
  flutter_inapp_notifications: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  copy_with_extension_gen: ^5.0.0
  build_runner: ^2.1.7
  flutter_launcher_icons: "^0.13.1"
  names_launcher: ^0.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "../branding/palcka2.png"
  min_sdk_android: 21
  web:
    generate: true
  windows:
    generate: true
    icon_size: 48
names_launcher:
  name: "Palčka"
  platforms:
    android:
      enable: true
    ios:
      enable: false
    linux:
      enable: false
    macos:
      enable: false
    windows:
      enable: true
    web:
      enable: true

flutter:
  uses-material-design: true
  assets:
    - assets/tarok/taroki/
    - assets/tarok/kara/
    - assets/tarok/kriz/
    - assets/tarok/pik/
    - assets/tarok/src/
    - assets/icons/
    - assets/zvoki/
