name: stockskis
description: Stock≈†kis, Tarock engine.
version: 1.0.0
repository: https://github.com/mytja/Tarok

environment:
  sdk: ^3.1.0-315.0.dev

# Add regular dependencies here.
dependencies:
  logger: ^2.0.1
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
