name: Build Windows app

on:
  push:
    branches: main

jobs:
  build:
    name: Build .exe for Windows
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ./tarok
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter pub upgrade
      - run: flutter pub get
      - run: flutter config --enable-windows-desktop
      - run: flutter doctor --verbose
      - run: flutter devices
      - run: flutter build windows --verbose
      - uses: actions/upload-artifact@v1
        with:
          name: windows_app
          path: build\windows\runner\Release\
